site_name: Giskard

theme:
  name: "material"

plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            show_source: true
#            heading_level: 1
            show_root_heading: true
            show_category_heading: true
            show_object_full_path: true

