version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.10"
  jobs:
    #    pre_build:
    ##      - sphinx-apidoc -o python-client/docs python-client/giskard
    post_create_environment:
      - pip install pdm
      - pdm config python.use_venv false
    post_install:
      - cd python-client && pdm install -G doc
#      - pip install -r python-client/requirements.txt


sphinx:
  configuration: python-client/docs/conf.py