version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.10"
  jobs:
    post_create_environment:
      - pip install pdm
      - pdm config python.use_venv false
    post_install:
      - pdm install -p python-client -G doc

sphinx:
  configuration: python-client/docs/conf.py
