version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.10"
  jobs:
    #    pre_build:
    ##      - sphinx-apidoc -o python-client/docs python-client/giskard
    post_create_environment:
      - pip install pdm
      - which python
#      - pdm config python.use_venv false
    post_install:
      - sh -c "which python && pdm config python.use_venv false && cd python-client && pdm info && pdm install -G doc && pdm config && pip list"
#      - pip install -r python-client/requirements.txt


sphinx:
  configuration: python-client/docs/conf.py