version: "3.8"
services:

  db:
    image: postgres:12-alpine
    volumes:
      - app-db-data:/var/lib/postgresql/data/pgdata
    env_file:
      - .env
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata

  backend:
    image: '${DOCKER_REGISTRY}/giskard-backend:${TAG-latest}'
    volumes:
      - app-files-bucket:/app/files-bucket
    depends_on:
      - db
    env_file:
      - .env
    environment:
      - SERVER_NAME=${DOMAIN?Variable not set}
      - SERVER_HOST=https://${DOMAIN?Variable not set}
      # Allow explicit env var override for tests
      - SMTP_HOST=${SMTP_HOST}

  ml-worker:
    image: '${DOCKER_REGISTRY}/ml-worker:${TAG-latest}'
    environment:
      - GSK_ENVIRONMENT=prod
      - GSK_STORAGE_ROOT=/app
      - GSK_PORT=50000
    volumes:
      - app-files-bucket:/app/files-bucket

  backend-java:
    image: '${DOCKER_REGISTRY}/backend-java:${TAG-latest}'
    env_file:
      - .env
    environment:
      - _JAVA_OPTIONS=-Xmx2048m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=y1QYbF2BtFUC
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/app
      - SPRING_LIQUIBASE_URL=jdbc:postgresql://db:5432/app
      - APPLICATION_ML_WORKER_HOST=ml-worker
      - APPLICATION_ML_WORKER_PORT=50000
    command: [ "/giskard/wait-for-python-app.sh", "backend", "java", "-jar","/giskard/lib/giskard.jar" ]


  frontend:
    image: '${DOCKER_REGISTRY}/giskard-frontend:${TAG-latest}'
    ports:
      - "19000:80"
    expose:
      - 19000
    depends_on:
      - backend
      - backend-java
    env_file:
      - .env

  jupyter:
    image: '${DOCKER_REGISTRY}/giskard-jupyter:${TAG-latest}'
    entrypoint:
      - /usr/local/bin/start.sh
      - jupyter
      - notebook
      - --NotebookApp.token=''
    volumes:
      - ./backend/demo-notebook/notebook:/home/jovyan
    ports:
      - '18888:8888'

volumes:
  app-db-data:
  app-files-bucket:
