version: "3.8"
services:

  db:
    ports:
      - "5432:5432"

  jupyter:
    build:
      context: ./giskard-demo-notebook
      dockerfile: demo-notebook.dockerfile

  frontend:
    platform: linux/amd64
    build:
      context: giskard-frontend
      dockerfile: Dockerfile
      args:
        FRONTEND_ENV: ${FRONTEND_ENV-production}

  ml-worker:
    build:
      context: .
      dockerfile: ./giskard-ml-worker/ml-worker.dockerfile

  backend:
    build:
      dockerfile: ./giskard-server/src/main/docker/app/app.dockerfile
      context: .
      args:
        RUN_TESTS: ${RUN_TESTS-false}