version: "3.8"
services:

  db:
    ports:
      - "5432:5432"

  jupyter:
    build:
      context: ./backend/demo-notebook
      dockerfile: demo-notebook.dockerfile

  frontend:
    platform: linux/amd64
    build:
      context: ./frontend
      args:
        FRONTEND_ENV: ${FRONTEND_ENV-production}

  backend:
    volumes:
      - ./backend/app:/app
    command: /start-reload.sh
    build:
      context: ./backend
      dockerfile: ./app/app.dockerfile
      args:
        INSTALL_DEV: ${INSTALL_DEV-false}

  ml-worker:
    build:
      context: ./backend
      dockerfile: ./ml-worker/ml-worker.dockerfile

  backend-java:
    build:
      dockerfile: ./java-app/src/main/docker/app/app.dockerfile
      context: ./backend