# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1
orbs:
  win: circleci/windows@5.0.0


# https://circleci.com/docs/reusing-config/#example-of-using-an-executor-declared-in-configyml-with-matrix-jobs
executors:
  # here we can define an executor that will be shared across different jobs
  ubuntu:
    parameters:
      python-version:
        description: "Python version"
        type: string
    docker:
      - image: cimg/python:<<parameters.python-version>>
    environment:
      GSK_DISABLE_ANALYTICS: "True"
      GISKARD_DEV_MODE: "True"
    resource_class: medium
  windows:
    machine:
      image: windows-server-2022-gui
    # resource_class: medium
    parameters:
      python-version:
        description: "Python version"
        type: string
    environment:
      GSK_DISABLE_ANALYTICS: "True"
      GISKARD_DEV_MODE: "True"
  macos:
    parameters:
      python-version:
        description: "Python version"
        type: string
    macos:
      xcode: 14.2.0
    environment:
      GSK_DISABLE_ANALYTICS: "True"
      GISKARD_DEV_MODE: "True"
    resource_class: medium

# Define a job to be invoked later in a workflow.
commands:
  install-pdm:
    description: "Install PDM"
    parameters:
      os:
        type: string
    steps:
      - when:
          condition: <<parameters.os>> != "windows"
          steps:
            - run: curl -sSL https://pdm-project.org/install-pdm.py | python3 -
      - when:
          condition: <<parameters.os>> == "windows"
          steps:
            - run: (Invoke-WebRequest -Uri https://pdm-project.org/install-pdm.py -UseBasicParsing).Content | python3 -
  install-python:
    description: "Install PDM"
    parameters:
      os:
        type: string
      python-version:
        type: string
    steps:
      - when:
          name: "Install Python (Windows)"
          condition: <<parameters.os>> == "windows"
          steps:
            - run: choco install python --version=<<parameters.python-version>>
      - when:
          name: "Install Python (MacOs)"
          condition: <<parameters.os>> == "macos"
          steps:
            - run: (Invoke-WebRequest -Uri https://pdm-project.org/install-pdm.py -UseBasicParsing).Content | python3 -
      - install-pdm:
          os: <<parameters.os>>
# See: https://circleci.com/docs/configuration-reference/#jobs
jobs:
  install:
    parameters:
      python-version:
        type: string
      os:
        type: string
    executor:
      name: <<parameters.os>>
      python-version: <<parameters.python-version>>
    steps:
      - checkout
      - install-python:
          os: <<parameters.os>>
          python-version: <<parameters.python-version>>
      # Download and cache dependencies
      - restore_cache:
          keys:
            - python-<<parameters.os>>-<<parameters.python-version>>-{{ checksum "pdm.lock" }}
            - python-<<parameters.os>>-<<parameters.python-version>>
      - run:
          name: Install deps
          command: pdm install -G :all
      - save_cache:
          paths:
            - .venv
          key: python-<<parameters.os>>-<<parameters.python-version>>-{{ checksum "pdm.lock" }}
  unit-tests:
    parameters:
      python-version:
        type: string
      os:
        type: string
    executor:
      name: <<parameters.os>>
      python-version: <<parameters.python-version>>
    parallelism: 20
    steps:
      - checkout
      - install-python:
          os: <<parameters.os>>
          python-version: <<parameters.python-version>>
      # Download and cache dependencies
      - restore_cache:
          keys:
            - python-<<parameters.os>>-<<parameters.python-version>>-{{ checksum "pdm.lock" }}
      - run:
          name: Run tests
          command: |
            mkdir -p test-results
            TEST=$(find ./tests -type f | grep '.py$' | grep -v __ | grep -v '/fixtures/' |  grep -v conftest | circleci tests split --split-by=timings)
            pdm base-test -m 'not slow' --junitxml=test-results/junit.xml $TEST

      - store_test_results:
          path: test-results

# Orchestrate jobs using workflows
# See: https://circleci.com/docs/configuration-reference/#workflows
workflows:
  python-workflow:
    jobs:
      - install:
          name: install-<<matrix.os>>-<<matrix.python-version>>
          matrix:
            parameters:
              os: [ubuntu, windows]
              python-version: ["3.9.18", "3.10.13", "3.11.6"]
      - unit-tests:
          name: test-<<matrix.os>>-<<matrix.python-version>>
          matrix:
            parameters:
              os: [ubuntu, windows]
              python-version: ["3.9.18", "3.10.13", "3.11.6"]
          requires:
            - install-<<matrix.os>>-<<matrix.python-version>>
# https://circleci.com/docs/using-matrix-jobs/
# https://circleci.com/docs/configuration-reference/#dependencies-and-matrix-jobs