# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1
# https://circleci.com/docs/reusing-config/#example-of-using-an-executor-declared-in-configyml-with-matrix-jobs
executors:
  # here we can define an executor that will be shared across different jobs
  ubuntu:
    parameters:
      python-version:
        description: "Python version"
        type: string
    docker:
      - image: cimg/python:<<parameters.python-version>>
    environment:
      GSK_DISABLE_ANALYTICS: "True"
      GISKARD_DEV_MODE: "True"
    resource_class: medium
# https://circleci.com/developer/machine/image/windows-server-2022-gui
  windows:
    parameters:
      python-version:
        description: "Python version"
        type: string
    machine:
      image: 'windows-server-2022-gui:current'
      resource_class: windows.medium
      shell: powershell.exe -ExecutionPolicy Bypass
    environment:
      GSK_DISABLE_ANALYTICS: "True"
      GISKARD_DEV_MODE: "True"
  macos:
    parameters:
      python-version:
        description: "Python version"
        type: string
    macos:
      xcode: 14.2.0
      resource_class: macos.x86.medium.gen2
    environment:
      GSK_DISABLE_ANALYTICS: "True"
      GISKARD_DEV_MODE: "True"

# Define a job to be invoked later in a workflow.
commands:
  install-pdm:
    description: "Install PDM"
    parameters:
      os:
        type: string
    steps:
      - unless:
          condition:
            equal: [ "windows", <<parameters.os>>]
          steps:
            - run: curl -sSL https://pdm-project.org/install-pdm.py | python -
              # name: Install PDM (Linux or others)
      - when:
          condition:
            equal: [ "windows", <<parameters.os>>]
          steps:
            - run: (Invoke-WebRequest -Uri https://pdm-project.org/install-pdm.py -UseBasicParsing).Content | python -
              # name: Install PDM (Windows)
  install-python:
    description: "Install PDM"
    parameters:
      os:
        type: string
      python-version:
        type: string
    steps:
      - when:
          condition:
            equal: [ "windows", <<parameters.os>>]
          steps:
            - run: choco install python --version=<<parameters.python-version>> --allow-downgrade -y
      - when:
          condition:
            equal: [ "macos", <<parameters.os>>]
          steps:
            - run: brew install python@$(echo <<parameters.python-version>> | sed -e 's/^\([0-9]+\.[0-9]\)+\.[0-9]+.*$/\1/p')
      - install-pdm:
          os: <<parameters.os >>
# See: https://circleci.com/docs/configuration-reference/#jobs
jobs:
  install:
    parameters:
      python-version:
        type: string
      os:
        type: string
    executor:
      name: <<parameters.os>>
      python-version: <<parameters.python-version>>
    steps:
      - checkout
      - install-python:
          os: <<parameters.os>>
          python-version: <<parameters.python-version>>
      # Download and cache dependencies
      - restore_cache:
          keys:
            - python-<<parameters.os>>-<<parameters.python-version>>-{{ checksum "pdm.lock" }}
            - python-<<parameters.os>>-<<parameters.python-version>>
      - run:
          name: Install deps
          command: pdm install -G :all
      - save_cache:
          paths:
            - .venv
          key: python-<<parameters.os>>-<<parameters.python-version>>-{{ checksum "pdm.lock" }}
  unit-tests:
    parameters:
      python-version:
        type: string
      os:
        type: string
    executor:
      name: <<parameters.os>>
      python-version: <<parameters.python-version>>
    parallelism: 20
    steps:
      - checkout
      - install-python:
          os: <<parameters.os>>
          python-version: <<parameters.python-version>>
      # Download and cache dependencies
      - restore_cache:
          keys:
            - python-<<parameters.os>>-<<parameters.python-version>>-{{ checksum "pdm.lock" }}
      - run:
          name: Run tests
          command: |
            mkdir -p test-results
            TEST=$(find ./tests -type f | grep '.py$' | grep -v __ | grep -v '/fixtures/' |  grep -v conftest | circleci tests split --split-by=timings)
            pdm base-test -m 'not slow' --junitxml=test-results/junit.xml $TEST

      - store_test_results:
          path: test-results

# Orchestrate jobs using workflows
# See: https://circleci.com/docs/configuration-reference/#workflows
workflows:
  python-workflow:
    jobs:
      - install:
          name: install-<<matrix.os>>-<<matrix.python-version>>
          matrix:
            parameters:
              os: [ubuntu, windows, macos]
              python-version: ["3.9.13", "3.10.11", "3.11.6"]
      - unit-tests:
          name: test-<<matrix.os>>-<<matrix.python-version>>
          matrix:
            parameters:
              os: [ubuntu, windows, macos]
              python-version: ["3.9.13", "3.10.11", "3.11.6"]
          requires:
            - install-<<matrix.os>>-<<matrix.python-version>>
# https://circleci.com/docs/using-matrix-jobs/
# https://circleci.com/docs/configuration-reference/#dependencies-and-matrix-jobs