name: Build Docker images and push to registry with dev tag

on:
  push:
    branches:
    - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-images:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Extract branch name
      shell: bash
      run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      id: extract_branch

    - name: Generate docker config file
      env:
        TAG: dev
      run: |
        sudo sysctl -w kernel.unprivileged_userns_clone=1
        docker-compose -f docker-compose.yml -f docker-compose.dev.yml config > docker-stack.yml 
      
    - name: Build images
      run: docker-compose -f docker-stack.yml build

    - name: Login to Docker registry
      uses: docker/login-action@v2
      if: ${{ steps.extract_branch.outputs.branch == 'main' }}
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Push images to Docker registry
      if: ${{ steps.extract_branch.outputs.branch == 'main' }}
      env:
        TAG: dev
      run: |
        docker-compose -f docker-compose.yml -f docker-compose.dev.yml push

    - name: Invoke deployment hook
      run: |
        curl -L --silent --max-time 900 ${{ secrets.TEST_SERVER_WEBHOOK_URL_BASE }}/redeploy-dev 

    - name: Remove containers and volumes
      run: docker-compose -f docker-stack.yml down -v --remove-orphans

