name: Build Docker images

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build-images:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set tag name
      id: tag
      run: |
        echo ::set-output name=name::${GITHUB_REF#refs/*/}
        echo ::set-output name=version::${GITHUB_REF#refs/*/v}
        echo ::set-output name=latest_version::$(git tag | grep -E "v\d+\.\d+\.\d+" | sort -hr | head -1)
#      run: echo ::set-output name=version::${GITHUB_REF#refs/*/*v}


    - name: test latest tag
#      if: ${{ steps.tag.outputs.name == steps.tag.outputs.latest_version }}
      id: publish_latest
      run: |
        echo LATEST: ${{steps.tag.outputs.latest_version}}
        echo CURRENT: ${{steps.tag.outputs.name}}
#
#
#
#    - name: Generate docker config file
#      env:
#        TAG: ${{ steps.tag.outputs.name }}
#      run: |
#        sudo sysctl -w kernel.unprivileged_userns_clone=1
#        docker-compose -f docker-compose.yml -f docker-compose.dev.yml config > docker-stack.yml
#
#    - name: Build images
#      run: docker-compose -f docker-stack.yml build --parallel
#
#    - name: Build images
#      run: docker-compose -f docker-stack.yml build --parallel
#
#    - name: Configure AWS credentials
#      uses: aws-actions/configure-aws-credentials@v1
#      with:
#        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
#        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#        aws-region: us-east-1
#
#    - name: Push images to ECR
#      run: |
#        aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/giskard
#        TAG=${{ steps.giskard_version.outputs.version }} docker-compose -f docker-compose.yml -f docker-compose.dev.yml push
#        TAG=latest docker-compose -f docker-compose.yml -f docker-compose.dev.yml push
#
#    - name: Remove containers and volumes
#      run: docker-compose -f docker-stack.yml down -v --remove-orphans
#
