name: Build Docker images and push to registry with dev tag

on:
  push:
    branches:
      - main
      - andrey/docker-buildx-auto-ec2
#  pull_request:
#    branches:
#      - main
  workflow_dispatch:

jobs:
  start-runner:
    name: Start self-hosted EC2 runner
    runs-on: ubuntu-latest
    outputs:
      label: ${{ steps.start-ec2-runner.outputs.label }}
      ec2-instance-id: ${{ steps.start-ec2-runner.outputs.ec2-instance-id }}
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.GH_RUNNER_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.GH_RUNNER_AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Start EC2 runner
        id: start-ec2-runner
        uses: machulav/ec2-github-runner@v2
        with:
          mode: start
          github-token: ${{ secrets.GH_RUNNER_PERSONAL_ACCESS_TOKEN }}
          ec2-image-id: ami-08c22f01e5d6c70aa
          ec2-instance-type: c7g.2xlarge
          subnet-id: subnet-1016f011
          security-group-id: sg-099313fa7d3f017ec
          aws-resource-tags: >
            [
              {"Key": "Name", "Value": "ec2-github-runner"},
              {"Key": "GitHubRepository", "Value": "${{ github.repository }}"}
            ]

  build-images:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3.1.0
        with:
          submodules: recursive

      - name: Set up Docker Buildx
        id: builder
        uses: docker/setup-buildx-action@master


      - name: "Append ARM buildx builder from AWS"
        uses: baschny/append-buildx-action@v1
        with:
          builder: ${{ steps.builder.outputs.name }}
          endpoint: ssh://${{ secrets.ARM_SSH_CONNECTION_STRING }}
          ssh_private_key: ${{ secrets.ARM_SSH_PRIVATE_KEY }}


      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch

      - name: Login to Docker registry
        uses: docker/login-action@v2
#        if: ${{ steps.extract_branch.outputs.branch == 'main' }}
        if: ${{ steps.extract_branch.outputs.branch == 'andrey/docker-buildx' }}
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/bake-action@master
        env:
          TAG: dev
        with:
#          push: ${{ steps.extract_branch.outputs.branch == 'main' }}
          push: ${{ steps.extract_branch.outputs.branch == 'andrey/docker-buildx' }}
          set: |
            *.platform=linux/amd64
            *.platform=linux/arm64

      - name: Invoke deployment hook
        if: ${{ steps.extract_branch.outputs.branch == 'main' }}
        run: |
          curl -L --silent --max-time 900 ${{ secrets.TEST_SERVER_WEBHOOK_URL_BASE }}/redeploy-dev

      - name: Remove containers and volumes
        run: |
          docker-compose down -v --remove-orphans
          docker builder prune --force --keep-storage=10GB
      

  stop-runner:
    name: Stop self-hosted EC2 runner
    needs:
      - start-runner
      - build-images
    runs-on: ubuntu-latest
    if: ${{ always() }} # required to stop the runner even if the error happened in the previous jobs
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.GH_RUNNER_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.GH_RUNNER_AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Stop EC2 runner
        uses: machulav/ec2-github-runner@v2
        with:
          mode: stop
          github-token: ${{ secrets.GH_RUNNER_PERSONAL_ACCESS_TOKEN }}
          label: ${{ needs.start-runner.outputs.label }}
          ec2-instance-id: ${{ needs.start-runner.outputs.ec2-instance-id }}
